import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'te' | 'ta' | 'kn' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Rich Static Dictionary for the Entire Web Application
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav & General
    'logo.title': 'Agri Farms',
    'nav.home': 'Home',
    'nav.rentals': 'Rentals',
    'nav.services': 'Services',
    'nav.activity': 'Activity',
    'nav.manage': 'Manage Assets',
    'nav.requests': 'Requests',
    'nav.profile': 'Profile',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Home Page
    'home.greeting': 'Namaste, {name}!',
    'home.selectField': 'Select Your Field',
    'home.detectLocation': 'Auto-Detect Field',
    'home.manualLocation': 'Enter Village/District',
    'home.searchPlaceholder': 'Search seeds, tractor, spraying services...',
    'home.searchBtn': 'Search',
    'home.seasonOffer': 'Season Offer',
    'home.bannerTitle': 'Book Modern Farm Services Today!',
    'home.bannerDesc': 'Professional drone sprayers, harvesters, and high-efficiency planting assistants nearby.',
    'home.exploreBtn': 'Explore Now',
    'home.rentEquip': 'Rent Equipment',
    'home.viewAll': 'View All',
    'home.tractors': 'Tractors',
    'home.harvesters': 'Harvesters',
    'home.sprayers': 'Sprayers',
    'home.jcb': 'JCB',
    'home.listAssetTitle': 'List your assets & earn.',
    'home.listAssetDesc': 'Join over 5,000+ localized farm providers earning weekly by renting out spare tractors, seeders, utility trucks, or custom labor helpers.',
    'home.registerAssetBtn': 'Register Asset',
    'home.rentNowBtn': 'Rent Now',
    'home.howItWorks': 'How it works',
    
    // Quick Tools
    'tool.weather': 'Weather',
    'tool.cropAdvice': 'Crop Advice',
    'tool.mandiPrices': 'Mandi Prices',
    'tool.calculator': 'Calculator',
    'tool.comingSoon': 'The service will come in next updated.',
    
    // Rentals Page
    'rentals.title': 'Equipment Rentals',
    'rentals.desc': 'Find the best machinery for your farm',
    'rentals.searchPlaceholder': 'Search by brand or category...',
    'rentals.booked': 'Booked',
    'rentals.available': 'Available',
    'rentals.bookNow': 'Book Now',
    'rentals.empty': 'No Equipment Found',
    'rentals.adjustFilters': 'Try adjusting your search or filters',
    
    // Services Page
    'services.title': 'Agri Services',
    'services.desc': 'Hire professional agricultural services',
    'services.searchPlaceholder': 'Search agricultural services...',
    'services.callBtn': 'Call Provider',
    'services.empty': 'No Services Found',
    
    // Activity Page
    'activity.title': 'My Activity',
    'activity.desc': 'Track your bookings and rental history',
    'activity.upcoming': 'Upcoming',
    'activity.history': 'History',
    'activity.totalPaid': 'Total Paid',
    'activity.empty': 'No bookings found',
    'activity.emptyDesc': "You haven't made any bookings yet.",
    
    // Profile Page & Language Selection
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal profile and listings',
    'profile.personalInfo': 'Personal Information',
    'profile.address': 'Contact Address Details',
    'profile.fullName': 'Full Name',
    'profile.phone': 'Phone Number',
    'profile.gps': 'Detect GPS Location',
    'profile.save': 'Save Detailed Profile',
    'profile.edit': 'Edit Profile',
    'profile.changePhoto': 'Change Photo',
    'profile.management': 'Account Management',
    'profile.myAssets': 'My Assets',
    'profile.settings': 'Account Settings',
    'profile.security': 'Privacy & Security',
    'profile.selectLanguage': 'Choose Language',
    'profile.logoutBtn': 'Logout from Account',
    'profile.changeSuccess': 'Profile details successfully saved!',
    'profile.settingsDesc': 'Manage your account settings and preferences',
    'profile.myAssetsDesc': 'Manage your listed assets and resources',
    'profile.activityDesc': 'Track your booking and rental history',
    'profile.securityDesc': 'Manage your privacy, security, and credentials',
    'profile.noPhone': 'No phone number provided',
    'profile.noAddress': 'No address added yet.',
    'nav.notifications': 'Notifications',
    'notifications.title': 'Notifications',
    'notifications.unreadAlerts': '{count} unread alerts',
    'notifications.readAll': 'Read All',
    'notifications.close': 'Close Panel',
    'notifications.emptyTitle': 'All caught up!',
    'notifications.emptyDesc': 'No new notifications or alerts at this moment.',
    'rentals.filters': 'Filters',
    'rentals.all': 'All',
    'rentals.plough': 'Ploughs',
    'rentals.seeder': 'Seeders',
    'services.transport': 'Transport',
    'services.workers': 'Workers',
    'services.addBtn': '+ Add New Equipment',
    'services.placeholder': 'Search for services, vehicles, or labor...',
    'activity.refresh': 'Refresh Activity',
    'activity.upcomingTitle': 'Upcoming ({count})',
    'activity.historyTitle': 'History ({count})',
    'activity.paid': 'Total Paid',
    'activity.emptyLabel': 'No bookings found',
    'activity.emptySub': "You haven't made any bookings yet.",
    'activity.exploreRentals': 'Explore Rentals',
    'activity.status.pending': 'PENDING',
    'activity.status.confirmed': 'CONFIRMED',
    'activity.status.rejected': 'REJECTED',
    'activity.status.completed': 'COMPLETED',
    'manage.title': 'Manage Assets',
    'manage.subtitle': 'Track and update your listed resources',
    'manage.addBtn': 'Add Asset',
    'manage.tab.vehicles': 'Vehicles',
    'manage.tab.equipment': 'Equipment',
    'manage.tab.services': 'Services',
    'manage.tab.workers': 'Workers',
    'manage.emptyTitle': 'No {tab} registered',
    'manage.emptyDesc': 'Add your assets to start earning on the platform',
    'manage.status.approved': 'APPROVED',
    'manage.status.rejected': 'REJECTED',
    'manage.status.pending': 'PENDING',
    'manage.confirmDelete': 'Are you sure you want to delete this item?',
    'manage.failedDelete': 'Failed to delete item',
    'role.farmer': 'Farmer',
    'role.owner': 'Owner',
    'role.provider': 'Provider / Specialist',
    'settings.title': 'Account Settings',
    'settings.subtitle': 'Manage your language and preferences',
    'settings.chooseLanguage': 'Choose Language',
    'settings.notificationPrefs': 'Notification Preferences',
    'settings.accSecurity': 'Account Privacy & Security',
    'settings.deleteAcc': 'Delete Account',
  },
  hi: {
    // Nav & General
    'logo.title': 'एग्री फार्म्स',
    'nav.home': 'मुख्य पृष्ठ',
    'nav.rentals': 'किराया',
    'nav.services': 'सेवाएं',
    'nav.activity': 'गतिविधि',
    'nav.manage': 'संपत्ति प्रबंधन',
    'nav.requests': 'अनुरोध',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',
    
    // Home Page
    'home.greeting': 'नमस्ते, {name}!',
    'home.selectField': 'अपना खेत चुनें',
    'home.detectLocation': 'जीपीएस स्थान का पता लगाएं',
    'home.manualLocation': 'गांव/जिला दर्ज करें',
    'home.searchPlaceholder': 'बीज, ट्रैक्टर, छिड़काव सेवाओं की खोज करें...',
    'home.searchBtn': 'खोजें',
    'home.seasonOffer': 'सीजन ऑफर',
    'home.bannerTitle': 'आज ही आधुनिक कृषि सेवाएं बुक करें!',
    'home.bannerDesc': 'पास में पेशेवर ड्रोन स्प्रेयर, हार्वेस्टर और उच्च दक्षता वाले रोपण सहायक उपलब्ध हैं।',
    'home.exploreBtn': 'अभी अन्वेषण करें',
    'home.rentEquip': 'उपकरण किराए पर लें',
    'home.viewAll': 'सभी देखें',
    'home.tractors': 'ट्रैक्टर',
    'home.harvesters': 'हार्वेस्टर',
    'home.sprayers': 'स्प्रेयर',
    'home.jcb': 'जेसीबी',
    'home.listAssetTitle': 'अपनी संपत्ति की सूची बनाएं और कमाएं।',
    'home.listAssetDesc': 'स्पेयर ट्रैक्टर, सीडर, उपयोगिता ट्रक, या कस्टम श्रम सहायकों को किराए पर देकर साप्ताहिक कमाई करने वाले 5,000+ स्थानीय कृषि प्रदाताओं में शामिल हों।',
    'home.registerAssetBtn': 'पंजीकरण करें',
    'home.rentNowBtn': 'किराए पर लें',
    'home.howItWorks': 'यह कैसे काम करता है',
    
    // Quick Tools
    'tool.weather': 'मौसम',
    'tool.cropAdvice': 'फसल सलाह',
    'tool.mandiPrices': 'मंडी भाव',
    'tool.calculator': 'कैलकुलेटर',
    'tool.comingSoon': 'यह सेवा अगले अपडेट में उपलब्ध होगी।',
    
    // Rentals Page
    'rentals.title': 'उपकरण किराया',
    'rentals.desc': 'अपने खेत के लिए सबसे अच्छी मशीनरी ढूंढें',
    'rentals.searchPlaceholder': 'ब्रांड या श्रेणी द्वारा खोजें...',
    'rentals.booked': 'बुक किया गया',
    'rentals.available': 'उपलब्ध',
    'rentals.bookNow': 'अभी बुक करें',
    'rentals.empty': 'कोई उपकरण नहीं मिला',
    'rentals.adjustFilters': 'अपनी खोज या फ़िल्टर को समायोजित करने का प्रयास करें',
    
    // Services Page
    'services.title': 'कृषि सेवाएं',
    'services.desc': 'पेशेवर कृषि सेवाएं किराए पर लें',
    'services.searchPlaceholder': 'कृषि सेवाओं की खोज करें...',
    'services.callBtn': 'प्रदाता को कॉल करें',
    'services.empty': 'कोई सेवा नहीं मिली',
    
    // Activity Page
    'activity.title': 'मेरी गतिविधि',
    'activity.desc': 'अपने बुकिंग और किराये के इतिहास को ट्रैक करें',
    'activity.upcoming': 'आगामी',
    'activity.history': 'इतिहास',
    'activity.totalPaid': 'कुल भुगतान',
    'activity.empty': 'कोई बुकिंग नहीं मिली',
    'activity.emptyDesc': 'आपने अभी तक कोई बुकिंग नहीं की है।',
    
    // Profile Page & Language Selection
    'profile.title': 'मेरी प्रोफ़ाइल',
    'profile.subtitle': 'अपनी व्यक्तिगत प्रोफ़ाइल और लिस्टिंग प्रबंधित करें',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.address': 'संपर्क पता विवरण',
    'profile.fullName': 'पूरा नाम',
    'profile.phone': 'फ़ोन नंबर',
    'profile.gps': 'जीपीएस स्थान का पता लगाएं',
    'profile.save': 'प्रोफ़ाइल सहेजें',
    'profile.edit': 'प्रोफ़ाइल संपादित करें',
    'profile.changePhoto': 'फ़ोटो बदलें',
    'profile.management': 'खाता प्रबंधन',
    'profile.myAssets': 'मेरी संपत्तियां',
    'profile.settings': 'खाता सेटिंग्स',
    'profile.security': 'गोपनीयता और सुरक्षा',
    'profile.selectLanguage': 'भाषा चुनें',
    'profile.logoutBtn': 'खाते से लॉगआउट करें',
    'profile.changeSuccess': 'प्रोफ़ाइल विवरण सफलतापूर्वक सहेजा गया!',
    'profile.settingsDesc': 'अपनी खाता सेटिंग्स और प्राथमिकताएं प्रबंधित करें',
    'profile.myAssetsDesc': 'अपनी सूचीबद्ध संपत्तियों और संसाधनों का प्रबंधन करें',
    'profile.activityDesc': 'अपने बुकिंग और किराये के इतिहास को ट्रैक करें',
    'profile.securityDesc': 'अपनी गोपनीयता, सुरक्षा और क्रेडेंशियल प्रबंधित करें',
    'profile.noPhone': 'कोई फ़ोन नंबर प्रदान नहीं किया गया',
    'profile.noAddress': 'अभी तक कोई पता नहीं जोड़ा गया है।',
    'nav.notifications': 'सूचनाएं',
    'notifications.title': 'सूचनाएं',
    'notifications.unreadAlerts': '{count} बिना पढ़ी सूचनाएं',
    'notifications.readAll': 'सभी पढ़ें',
    'notifications.close': 'पैनल बंद करें',
    'notifications.emptyTitle': 'सब पूरा हो गया!',
    'notifications.emptyDesc': 'इस समय कोई नई सूचना या अलर्ट नहीं है।',
    'rentals.filters': 'फ़िल्टर',
    'rentals.all': 'सभी',
    'rentals.plough': 'हल',
    'rentals.seeder': 'सीडर',
    'services.transport': 'परिवहन',
    'services.workers': 'मजदूर',
    'services.addBtn': '+ नए उपकरण जोड़ें',
    'services.placeholder': 'सेवाएं, वाहन या श्रम खोजें...',
    'activity.refresh': 'गतिविधि रीफ्रेश करें',
    'activity.upcomingTitle': 'आगामी ({count})',
    'activity.historyTitle': 'इतिहास ({count})',
    'activity.paid': 'कुल भुगतान किया',
    'activity.emptyLabel': 'कोई बुकिंग नहीं मिली',
    'activity.emptySub': 'आपने अभी तक कोई बुकिंग नहीं की है।',
    'activity.exploreRentals': 'किराए का अन्वेषण करें',
    'activity.status.pending': 'लंबित',
    'activity.status.confirmed': 'पुष्टि की गई',
    'activity.status.rejected': 'अस्वीकृत',
    'activity.status.completed': 'पूरा हुआ',
    'manage.title': 'संपत्ति प्रबंधन',
    'manage.subtitle': 'अपनी सूचीबद्ध संपत्तियों को ट्रैक और अपडेट करें',
    'manage.addBtn': 'संपत्ति जोड़ें',
    'manage.tab.vehicles': 'वाहन',
    'manage.tab.equipment': 'उपकरण',
    'manage.tab.services': 'सेवाएं',
    'manage.tab.workers': 'श्रमिक',
    'manage.emptyTitle': 'कोई {tab} पंजीकृत नहीं है',
    'manage.emptyDesc': 'कमाई शुरू करने के लिए अपनी संपत्तियां जोड़ें',
    'manage.status.approved': 'स्वीकृत',
    'manage.status.rejected': 'अस्वीकृत',
    'manage.status.pending': 'लंबित',
    'manage.confirmDelete': 'क्या आप वाकई इस आइटम को हटाना चाहते हैं?',
    'manage.failedDelete': 'आइटम को हटाने में विफल',
    'role.farmer': 'किसान',
    'role.owner': 'मालिक',
    'role.provider': 'प्रदाता / विशेषज्ञ',
    'settings.title': 'खाता सेटिंग्स',
    'settings.subtitle': 'अपनी भाषा और प्राथमिकताएं प्रबंधित करें',
    'settings.chooseLanguage': 'भाषा चुनें',
    'settings.notificationPrefs': 'अधिसूचना प्राथमिकताएं',
    'settings.accSecurity': 'खाता गोपनीयता और सुरक्षा',
    'settings.deleteAcc': 'खाता हटाएं',
  },
  te: {
    // Nav & General
    'logo.title': 'అగ్రి ఫార్మ్స్',
    'nav.home': 'హోమ్',
    'nav.rentals': 'అద్దెలు',
    'nav.services': 'సేవలు',
    'nav.activity': 'కార్యాచరణ',
    'nav.manage': 'ఆస్తుల నిర్వహణ',
    'nav.profile': 'ప్రొఫైల్',
    'nav.login': 'లాగిన్',
    'nav.logout': 'లాగౌట్',
    
    // Home Page
    'home.greeting': 'నమస్తే, {name}!',
    'home.selectField': 'మీ పొలాన్ని ఎంచుకోండి',
    'home.detectLocation': 'జీపీఎస్ స్థానాన్ని గుర్తించండి',
    'home.manualLocation': 'గ్రామం/జిల్లా నమోదు చేయండి',
    'home.searchPlaceholder': 'విత్తనాలు, ట్రాక్టర్, పిచికారీ సేవలను శోధించండి...',
    'home.searchBtn': 'శోధన',
    'home.seasonOffer': 'సీజన్ ఆఫర్',
    'home.bannerTitle': 'ఈరోజే ఆధునిక వ్యవసాయ సేవలను బుక్ చేసుకోండి!',
    'home.bannerDesc': 'వృత్తిపరమైన డ్రోన్ స్ప్రేయర్లు, హార్వెస్టర్లు మరియు అధిక సామర్థ్యం గల నాటడం సహాయకులు అందుబాటులో ఉన్నారు.',
    'home.exploreBtn': 'ఇప్పుడే అన్వేషించండి',
    'home.rentEquip': 'వ్యవసాయ పరికరాలు',
    'home.viewAll': 'అన్నీ చూడండి',
    'home.tractors': 'ట్రాక్టర్లు',
    'home.harvesters': 'హార్వెస్టర్లు',
    'home.sprayers': 'స్ప్రేయర్లు',
    'home.jcb': 'జేసీబీ',
    'home.listAssetTitle': 'మీ ఆస్తులను జాబితా చేయండి & సంపాదించండి.',
    'home.listAssetDesc': 'అదనపు ట్రాక్టర్లు, సీడర్లు, యుటిలిటీ ట్రక్కులు లేదా అనుకూల లేబర్ సహాయకులను అద్దెకు ఇవ్వడం ద్వారా వారానికొకసారి సంపాదిస్తున్న 5,000+ స్థానిక వ్యవసాయ ప్రదాతలలో చేరండి.',
    'home.registerAssetBtn': 'ఆస్తిని నమోదు చేయండి',
    'home.rentNowBtn': 'అద్దెకు తీసుకోండి',
    'home.howItWorks': 'ఇది ఎలా పనిచేస్తుంది',
    
    // Quick Tools
    'tool.weather': 'వాతావరణం',
    'tool.cropAdvice': 'పంట సలహా',
    'tool.mandiPrices': 'మండి ధరలు',
    'tool.calculator': 'క్యాలిక్యులేటర్',
    'tool.comingSoon': 'ఈ సేవ తదుపరి అప్‌డేట్‌లో అందుబాటులోకి వస్తుంది.',
    
    // Rentals Page
    'rentals.title': 'పరికరాల అద్దెలు',
    'rentals.desc': 'మీ పొలం కోసం ఉత్తమమైన యంత్రాలను కనుగొనండి',
    'rentals.searchPlaceholder': 'బ్రాండ్ లేదా వర్గం ద్వారా శోధించండి...',
    'rentals.booked': 'బుక్ చేయబడింది',
    'rentals.available': 'అందుబాటులో ఉంది',
    'rentals.bookNow': 'ఇప్పుడే బుక్ చేయండి',
    'rentals.empty': 'పరికరాలు ఏవీ కనుగొనబడలేదు',
    'rentals.adjustFilters': 'మీ శోధన లేదా ఫిల్టర్‌లను సర్దుబాటు చేయడానికి ప్రయత్నించండి',
    
    // Services Page
    'services.title': 'వ్యవసాయ సేవలు',
    'services.desc': 'వృత్తిపరమైన వ్యవసాయ సేవలను అద్దెకు తీసుకోండి',
    'services.searchPlaceholder': 'వ్యవసాయ సేవలను శోధించండి...',
    'services.callBtn': 'ప్రొవైడర్‌కు కాల్ చేయండి',
    'services.empty': 'సేవలు ఏవీ కనుగొనబడలేదు',
    
    // Activity Page
    'activity.title': 'నా కార్యాచరణ',
    'activity.desc': 'మీ బుకింగ్స్ మరియు అద్దె చరిత్రను ట్రాక్ చేయండి',
    'activity.upcoming': 'రాబోయేవి',
    'activity.history': 'చరిత్ర',
    'activity.totalPaid': 'మొత్తం చెల్లించారు',
    'activity.empty': 'బుకింగ్‌లు ఏవీ కనుగొనబడలేదు',
    'activity.emptyDesc': 'మీరు ఇంకా ఎలాంటి బుకింగ్‌లు చేయలేదు.',
    
    // Profile Page & Language Selection
    'profile.title': 'నా ప్రొఫైల్',
    'profile.subtitle': 'మీ వ్యక్తిగత ప్రొఫైల్ మరియు జాబితాలను నిర్వహించండి',
    'profile.personalInfo': 'వ్యక్తిగత సమాచారం',
    'profile.address': 'సంప్రదింపు చిరునామా వివరాలు',
    'profile.fullName': 'పూర్తి పేరు',
    'profile.phone': 'ఫోన్ నంబర్',
    'profile.gps': 'జీపీఎస్ స్థానాన్ని గుర్తించండి',
    'profile.save': 'ప్రొఫైల్‌ను సేవ్ చేయి',
    'profile.edit': 'ప్రొఫైల్‌ను సవరించు',
    'profile.changePhoto': 'ఫోటో మార్చండి',
    'profile.management': 'ఖాతా నిర్వహణ',
    'profile.myAssets': 'నా ఆస్తులు',
    'profile.settings': 'ఖాతా సెట్టింగులు',
    'profile.security': 'గోప్యత & భద్రత',
    'profile.selectLanguage': 'భాషను ఎంచుకోండి',
    'profile.logoutBtn': 'ఖాతా నుండి లాగౌట్ అవ్వండి',
    'profile.changeSuccess': 'ప్రొఫైల్ వివరాలు విజయవంతంగా సేవ్ చేయబడ్డాయి!',
    'profile.settingsDesc': 'మీ ఖాతా సెట్టింగ్‌లు మరియు ప్రాధాన్యతలను నిర్వహించండి',
    'profile.myAssetsDesc': 'మీ జాబితా చేయబడిన ఆస్తులు మరియు వనరులను నిర్వహించండి',
    'profile.activityDesc': 'మీ బుకింగ్ మరియు అద్దె చరిత్రను ట్రాక్ చేయండి',
    'profile.securityDesc': 'మీ గోప్యత, భద్రత మరియు ఆధారాలను నిర్వహించండి',
    'profile.noPhone': 'ఫోన్ నంబర్ అందించబడలేదు',
    'profile.noAddress': 'ఇంకా చిరునామా జోడించబడలేదు.',
    'nav.notifications': 'నోటిఫికேషన్లు',
    'notifications.title': 'నోటిఫിക്കేషన్లు',
    'notifications.unreadAlerts': '{count} చదవని అలర్ట్‌లు',
    'notifications.readAll': 'అన్నీ చదివినట్లు మార్క్ చేయి',
    'notifications.close': 'ప్యానెల్ మూసివేయి',
    'notifications.emptyTitle': 'అన్నీ పూర్తయ్యాయి!',
    'notifications.emptyDesc': 'ఈ సమయంలో కొత్త నోటిఫికேషన్‌లు లేదా అలర్ట్‌లు లేవు.',
    'rentals.filters': 'ఫిల్టర్లు',
    'rentals.all': 'అన్నీ',
    'rentals.plough': 'నాగళ్ళు',
    'rentals.seeder': 'సీడర్లు',
    'services.transport': 'రవాణా',
    'services.workers': 'కూలీలు',
    'services.addBtn': '+ కొత్త పరికరాన్ని జోడించు',
    'services.placeholder': 'సేవలు, వాహనాలు లేదా కూలీల కోసం వెతకండి...',
    'activity.refresh': 'కార్యాచరణను రీఫ్రెష్ చేయి',
    'activity.upcomingTitle': 'రాబోయేవి ({count})',
    'activity.historyTitle': 'చరిత్ర ({count})',
    'activity.paid': 'మొత్తం చెల్లించారు',
    'activity.emptyLabel': 'బుకింగ్‌లు ఏవీ కనుగొనబడలేదు',
    'activity.emptySub': 'మీరు ఇంకా ఎలాంటి బుకింగ్‌లు చేయలేదు.',
    'activity.exploreRentals': 'అద్దెలను అన్వేషించండి',
    'activity.status.pending': 'పెండింగ్',
    'activity.status.confirmed': 'ధృవీకరించబడింది',
    'activity.status.rejected': 'తిరస్కరించబడింది',
    'activity.status.completed': 'పూర్తయింది',
    'manage.title': 'ఆస్తుల నిర్వహణ',
    'manage.subtitle': 'మీ జాబಿತా చేయబడిన వనరులను ట్రాక్ చేయండి మరియు నవీకరించండి',
    'manage.addBtn': 'ఆస్తిని జోడించు',
    'manage.tab.vehicles': 'వాహనాలు',
    'manage.tab.equipment': 'పరికరాలు',
    'manage.tab.services': 'సేవలు',
    'manage.tab.workers': 'కూలీల సమూహాలు',
    'manage.emptyTitle': 'ఏ {tab} నమోదు చేయబడలేదు',
    'manage.emptyDesc': 'ప్లాట్‌ఫారమ్‌లో సంపాదించడం ప్రారంభించడానికి మీ ఆస్తులను జోడించండి',
    'manage.status.approved': 'ఆమోదించబడింది',
    'manage.status.rejected': 'తిరಸ್ಕరించబడింది',
    'manage.status.pending': 'పెండింగ్',
    'manage.confirmDelete': 'మీరు ఖచ్చితంగా ఈ వస్తువును తొலగించాలనుకుంటున్నారా?',
    'manage.failedDelete': 'తొలగించడం విఫలమైంది',
    'role.farmer': 'రైతు',
    'role.owner': 'యజమాని',
    'role.provider': 'ప్రొవైడర్ / నిపుణుడు',
    'settings.title': 'ఖాతా సెట్టింగులు',
    'settings.subtitle': 'మీ భాష మరియు ప్రాధాన్యతలను నిర్వహించండి',
    'settings.chooseLanguage': 'భాషను ఎంచుకోండి',
    'settings.notificationPrefs': 'నోటిఫికேషన్ ప్రాధాన్యతలు',
    'settings.accSecurity': 'ఖాతా గోప్యత & భద్రత',
    'settings.deleteAcc': 'ఖాతాను తొలగించు',
  },
  ta: {
    // Nav & General
    'logo.title': 'அக்ரி ஃபார்ம்ஸ்',
    'nav.home': 'முகப்பு',
    'nav.rentals': 'வாடகைகள்',
    'nav.services': 'சேவைகள்',
    'nav.activity': 'செயல்பாடு',
    'nav.manage': 'சொத்து மேலாண்மை',
    'nav.profile': 'சுயவிவரம்',
    'nav.login': 'உள்நுழை',
    'nav.logout': 'வெளியேறு',
    
    // Home Page
    'home.greeting': 'வணக்கம், {name}!',
    'home.selectField': 'உங்கள் வயலைத் தேர்ந்தெடுக்கவும்',
    'home.detectLocation': 'ஜிபிஎஸ் இருப்பிடத்தைக் கண்டறியவும்',
    'home.manualLocation': 'கிராமம்/மாவட்டத்தை உள்ளிடவும்',
    'home.searchPlaceholder': 'விதைகள், டிராக்டர், தெளிப்பு சேவைகளைத் தேடுங்கள்...',
    'home.searchBtn': 'தேடு',
    'home.seasonOffer': 'சீசன் ஆஃபர்',
    'home.bannerTitle': 'இன்றே நவீன விவசாய சேவைகளை முன்பதிவு செய்யுங்கள்!',
    'home.bannerDesc': 'தொழில்முறை ட்ரோன் தெளிப்பான்கள், அறுவடை இயந்திரங்கள் மற்றும் உயர் திறன் கொண்ட நடவு உதவியாளர்கள் அருகில் உள்ளனர்.',
    'home.exploreBtn': 'இப்போது ஆராயுங்கள்',
    'home.rentEquip': 'உபகரணங்கள் வாடகை',
    'home.viewAll': 'அனைத்தையும் பார்',
    'home.tractors': 'டிராக்டர்கள்',
    'home.harvesters': 'அறுவடை இயந்திரங்கள்',
    'home.sprayers': 'தெளிப்பான்கள்',
    'home.jcb': 'ஜேசிபி',
    'home.listAssetTitle': 'உங்கள் சொத்துக்களை பட்டியலிட்டு சம்பாதிக்கவும்.',
    'home.listAssetDesc': 'டிராக்டர்கள், விதைப்பான்கள், பயன்பாட்டு டிரக்குகள் அல்லது தனிப்பயன் தொழிலாளர் உதவியாளர்களை வாடகைக்கு விடுவதன் மூலம் வாராந்திர சம்பாதிக்கும் 5,000+ உள்ளூர் விவசாய வழங்குநர்களுடன் இணையுங்கள்.',
    'home.registerAssetBtn': 'சொத்தை பதிவு செய்யவும்',
    'home.rentNowBtn': 'இப்போது வாடகைக்கு',
    'home.howItWorks': 'இது எப்படி வேலை செய்கிறது',
    
    // Quick Tools
    'tool.weather': 'வானிலை',
    'tool.cropAdvice': 'பயிர் ஆலோசனை',
    'tool.mandiPrices': 'சந்தை விலைகள்',
    'tool.calculator': 'கணக்கீட்டாளர்',
    'tool.comingSoon': 'இந்த சேவை அடுத்த அப்டேட்டில் கிடைக்கும்.',
    
    // Rentals Page
    'rentals.title': 'உபகரணங்கள் வாடகை',
    'rentals.desc': 'உங்கள் பண்ணைக்கான சிறந்த இயந்திரங்களைக் கண்டறியவும்',
    'rentals.searchPlaceholder': 'பிராண்ட் அல்லது வகை மூலம் தேடவும்...',
    'rentals.booked': 'முன்பதிவு செய்யப்பட்டது',
    'rentals.available': 'கிடைக்கிறது',
    'rentals.bookNow': 'இப்போது முன்பதிவு செய்',
    'rentals.empty': 'உபகரணங்கள் எதுவும் காணப்படவில்லை',
    'rentals.adjustFilters': 'உங்கள் தேடல் அல்லது வடிப்பான்களை சரிசெய்ய முயற்சிக்கவும்',
    
    // Services Page
    'services.title': 'விவசாய சேவைகள்',
    'services.desc': 'தொழில்முறை விவசாய சேவைகளை வாடகைக்கு அமர்த்தவும்',
    'services.searchPlaceholder': 'விவசாய சேவைகளைத் தேடுங்கள்...',
    'services.callBtn': 'வழங்குநரை அழைக்கவும்',
    'services.empty': 'சேவைகள் எதுவும் காணப்படவில்லை',
    
    // Activity Page
    'activity.title': 'எனது செயல்பாடு',
    'activity.desc': 'உங்கள் முன்பதிவுகள் மற்றும் வாடகை வரலாற்றைக் கண்காணிக்கவும்',
    'activity.upcoming': 'வரவிருக்கும்',
    'activity.history': 'வரலாறு',
    'activity.totalPaid': 'மொத்தம் செலுத்தப்பட்டது',
    'activity.empty': 'முன்பதிவுகள் எதுவும் காணப்படவில்லை',
    'activity.emptyDesc': 'நீங்கள் இன்னும் எந்த முன்பதிவும் செய்யவில்லை.',
    
    // Profile Page & Language Selection
    'profile.title': 'எனது சுயவிவரம்',
    'profile.subtitle': 'உங்கள் தனிப்பட்ட சுயவிவரம் மற்றும் பட்டியல்களை நிர்வகிக்கவும்',
    'profile.personalInfo': 'தனிப்பட்ட தகவல்',
    'profile.address': 'தொடர்பு முகவரி விவரங்கள்',
    'profile.fullName': 'முழு பெயர்',
    'profile.phone': 'தொலைபேசி எண்',
    'profile.gps': 'ஜிபிஎஸ் இருப்பிடத்தைக் கண்டறியவும்',
    'profile.save': 'சுயவிவரத்தைச் சேமிக்கவும்',
    'profile.edit': 'சுயவிவரத்தைத் திருத்தவும்',
    'profile.changePhoto': 'புகைப்படத்தை மாற்று',
    'profile.management': 'கணக்கு மேலாண்மை',
    'profile.myAssets': 'எனது சொத்துக்கள்',
    'profile.settings': 'கணக்கு அமைப்புகள்',
    'profile.security': 'தனியுரிமை & பாதுகாப்பு',
    'profile.selectLanguage': 'மொழியைத் தேர்ந்தெடு',
    'profile.logoutBtn': 'கணக்கிலிருந்து வெளியேறவும்',
    'profile.changeSuccess': 'சுயவிவர விவரங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன!',
    'profile.settingsDesc': 'உங்கள் கணக்கு அமைப்புகள் மற்றும் விருப்பங்களை நிர்வகிக்கவும்',
    'profile.myAssetsDesc': 'பட்டியலிடப்பட்ட சொத்துக்கள் மற்றும் வளங்களை நிர்வகிக்கவும்',
    'profile.activityDesc': 'உங்கள் முன்பதிவு மற்றும் வாடகை வரலாற்றைக் கண்காணிக்கவும்',
    'profile.securityDesc': 'தனியுரிமை, பாதுகாப்பு மற்றும் சான்றுகளை நிர்வகிக்கவும்',
    'profile.noPhone': 'தொலைபேசி எண் வழங்கப்படவில்லை',
    'profile.noAddress': 'முகவரி இன்னும் சேர்க்கப்படவில்லை.',
    'nav.notifications': 'அறிவிப்புகள்',
    'notifications.title': 'அறிவிப்புகள்',
    'notifications.unreadAlerts': '{count} படிக்காத விழிப்பூட்டல்கள்',
    'notifications.readAll': 'அனைத்தையும் படியுங்கள்',
    'notifications.close': 'பேனலை மூடு',
    'notifications.emptyTitle': 'அனைத்தும் முடிந்தது!',
    'notifications.emptyDesc': 'இந்த நேரத்தில் புதிய அறிவிப்புகள் அல்லது விழிப்பூட்டல்கள் எதுவும் இல்லை.',
    'rentals.filters': 'வடிப்பான்கள்',
    'rentals.all': 'அனைத்தும்',
    'rentals.plough': 'கலப்பைகள்',
    'rentals.seeder': 'விதைப்பான்கள்',
    'services.transport': 'போக்குவரத்து',
    'services.workers': 'தொழிலாளர்கள்',
    'services.addBtn': '+ புதிய உபகரணங்களைச் சேர்க்கவும்',
    'services.placeholder': 'சேவைகள், வாகனங்கள் அல்லது தொழிலாளர்களைத் தேடுங்கள்...',
    'activity.refresh': 'செயல்பாட்டைப் புதுப்பி',
    'activity.upcomingTitle': 'வரவிருப்பவை ({count})',
    'activity.historyTitle': 'வரலாறு ({count})',
    'activity.paid': 'மொத்தம் செலுத்தப்பட்டது',
    'activity.emptyLabel': 'முன்பதிவுகள் எதுவும் காணப்படவில்லை',
    'activity.emptySub': 'நீங்கள் இன்னும் எந்த முன்பதிவு செய்வில்லை.',
    'activity.exploreRentals': 'வாடகைகளை ஆராயுங்கள்',
    'activity.status.pending': 'நிலுவையில் உள்ளது',
    'activity.status.confirmed': 'உறுதி செய்யப்பட்டது',
    'activity.status.rejected': 'நிராகரிக்கப்பட்டது',
    'activity.status.completed': 'நிறைவடைந்தது',
    'manage.title': 'சொத்துக்களை நிர்வகிக்கவும்',
    'manage.subtitle': 'பட்டியலிடப்பட்ட வளங்களைக் கண்காணித்து புதுப்பிக்கவும்',
    'manage.addBtn': 'சொத்தைச் சேர்க்கவும்',
    'manage.tab.vehicles': 'வாகனங்கள்',
    'manage.tab.equipment': 'உபகரணங்கள்',
    'manage.tab.services': 'சேவைகள்',
    'manage.tab.workers': 'தொழிலாளர்கள் குழுக்கள்',
    'manage.emptyTitle': 'பதிவு செய்யப்பட்ட {tab} எதுவும் இல்லை',
    'manage.emptyDesc': 'சம்பாதிக்கத் தொடங்க உங்கள் சொத்துக்களைச் சேர்க்கவும்',
    'manage.status.approved': 'அங்கீகரிக்கப்பட்டது',
    'manage.status.rejected': 'நிராகரிக்கப்பட்டது',
    'manage.status.pending': 'நிலுவையில் உள்ளது',
    'manage.confirmDelete': 'இந்த உருப்படியை நீக்க விரும்புகிறீர்களா?',
    'manage.failedDelete': 'உருப்படியை நீக்க முடியவில்லை',
    'role.farmer': 'விவசாயி',
    'role.owner': 'உரிமையாளர்',
    'role.provider': 'வழங்குநர் / நிபுணர்',
    'settings.title': 'கணக்கு அமைப்புகள்',
    'settings.subtitle': 'உங்கள் மொழி மற்றும் விருப்பங்களை நிர்வகிக்கவும்',
    'settings.chooseLanguage': 'மொழியைத் தேர்ந்தெடு',
    'settings.notificationPrefs': 'அறிவிப்பு விருப்பங்கள்',
    'settings.accSecurity': 'கணக்கு தனியுரிமை & பாதுகாப்பு',
    'settings.deleteAcc': 'கணக்கை நீக்கு',
  },
  kn: {
    // Nav & General
    'logo.title': 'ಅಗ್ರಿ ಫಾರ್ಮ್ಸ್',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.rentals': 'ಬಾಡಿಗೆಗಳು',
    'nav.services': 'ಸೇವೆಗಳು',
    'nav.activity': 'ಚಟುವಟಿಕೆ',
    'nav.manage': 'ಆಸ್ತಿ ನಿರ್ವಹಣೆ',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.login': 'ಲಾಗಿನ್',
    'nav.logout': 'ಲಾಗೌಟ್',
    
    // Home Page
    'home.greeting': 'ನಮಸ್ತೆ, {name}!',
    'home.selectField': 'ನಿಮ್ಮ ಕ್ಷೇತ್ರವನ್ನು ಆರಿಸಿ',
    'home.detectLocation': 'ಜಿಪಿಎಸ್ ಮೂಲಕ ಪತ್ತೆ ಮಾಡಿ',
    'home.manualLocation': 'ಗ್ರಾಮ/ಜಿಲ್ಲೆಯನ್ನು ನಮೂದಿಸಿ',
    'home.searchPlaceholder': 'ಬೀಜಗಳು, ಟ್ರ್ಯಾಕ್ಟರ್, ಸಿಂಪಡಿಸುವ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ...',
    'home.searchBtn': 'ಹುಡುಕಿ',
    'home.seasonOffer': 'ಸೀಸನ್ ಆಫರ್',
    'home.bannerTitle': 'ಇಂದೇ ಆಧುನಿಕ ಕೃಷಿ ಸೇವೆಗಳನ್ನು ಬುಕ್ ಮಾಡಿ!',
    'home.bannerDesc': 'ವೃತ್ತಿಪರ ಡ್ರೋನ್ ಸಿಂಪಡಕಗಳು, ಕೊಯ್ಲು ಯಂತ್ರಗಳು ಮತ್ತು ಹೆಚ್ಚಿನ ದಕ್ಷತೆಯ ನೆಡುವಿಕೆ ಸಹಾಯಕರು ಹತ್ತಿರದಲ್ಲಿದ್ದಾರೆ.',
    'home.exploreBtn': 'ಈಗಲೇ ಅನ್ವೇಷಿಸಿ',
    'home.rentEquip': 'ಉಪಕರಣಗಳ ಬಾಡಿಗೆ',
    'home.viewAll': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    'home.tractors': 'ಟ್ರ್ಯಾಕ್ಟರ್‌ಗಳು',
    'home.harvesters': 'ಕೊಯ್ಲು ಯಂತ್ರಗಳು',
    'home.sprayers': 'ಸಿಂಪಡಕಗಳು',
    'home.jcb': 'ಜೆಸಿಬಿ',
    'home.listAssetTitle': 'ನಿಮ್ಮ ಸ್ವತ್ತುಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ ಮತ್ತು ಗಳಿಸಿ.',
    'home.listAssetDesc': 'ಸ್ಪೇರ್ ಟ್ರ್ಯಾಕ್ಟರ್‌ಗಳು, ಸೀಡರ್‌ಗಳು, ಯುಟಿಲಿಟಿ ಟ್ರಕ್‌ಗಳು ಅಥವಾ ಕಸ್ಟಮ್ ಕಾರ್ಮಿಕ ಸಹಾಯಕರನ್ನು ಬಾಡಿಗೆಗೆ ನೀಡುವ ಮೂಲಕ ವಾರಕ್ಕೊಮ್ಮೆ ಗಳಿಸುತ್ತಿರುವ 5,000+ ಸ್ಥಳೀಯ ಕೃಷಿ ಪೂರೈಕೆದಾರರೊಂದಿಗೆ ಸೇರಿಕೊಳ್ಳಿ.',
    'home.registerAssetBtn': 'ಸ್ವತ್ತನ್ನು ನೋಂದಾಯಿಸಿ',
    'home.rentNowBtn': 'ಈಗಲೇ ಬಾಡಿಗೆ ಪಡೆಯಿರಿ',
    'home.howItWorks': 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    
    // Quick Tools
    'tool.weather': 'ಹವಾಮಾನ',
    'tool.cropAdvice': 'ಬೆಳೆ ಸಲಹೆ',
    'tool.mandiPrices': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    'tool.calculator': 'ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    'tool.comingSoon': 'ಈ ಸೇವೆಯು ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಲಭ್ಯವಿರುತ್ತದೆ.',
    
    // Rentals Page
    'rentals.title': 'ಉಪಕರಣಗಳ ಬಾಡಿಗೆಗಳು',
    'rentals.desc': 'ನಿಮ್ಮ ಫಾರ್ಮ್‌ಗಾಗಿ ಅತ್ಯುತ್ತಮ ಯಂತ್ರೋಪಕರಣಗಳನ್ನು ಹುಡುಕಿ',
    'rentals.searchPlaceholder': 'ಬ್ರ್ಯಾಂಡ್ ಅಥವಾ ವರ್ಗದ ಮೂಲಕ ಹುಡುಕಿ...',
    'rentals.booked': 'ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ',
    'rentals.available': 'ಲಭ್ಯವಿದೆ',
    'rentals.bookNow': 'ಈಗಲೇ ಬುಕ್ ಮಾಡಿ',
    'rentals.empty': 'ಯಾವುದೇ ಉಪಕರಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'rentals.adjustFilters': 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ',
    
    // Services Page
    'services.title': 'ಕೃಷಿ ಸೇವೆಗಳು',
    'services.desc': 'ವೃತ್ತಿಪರ ಕೃಷಿ ಸೇವೆಗಳನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ',
    'services.searchPlaceholder': 'ಕೃಷಿ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ...',
    'services.callBtn': 'ಪೂರೈಕೆದಾರರಿಗೆ ಕರೆ ಮಾಡಿ',
    'services.empty': 'ಯಾವುದೇ ಸೇವೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    
    // Activity Page
    'activity.title': 'ನನ್ನ ಚಟುವಟಿಕೆ',
    'activity.desc': 'ನಿಮ್ಮ ಬುಕಿಂಗ್ ಮತ್ತು ಬಾಡಿಗೆ ಇತಿಹಾಸವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'activity.upcoming': 'ಮುಂಬರುವ',
    'activity.history': 'ಇತಿಹಾಸ',
    'activity.totalPaid': 'ಒಟ್ಟು ಪಾವತಿಸಲಾಗಿದೆ',
    'activity.empty': 'ಯಾವುದೇ ಬುಕಿಂಗ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'activity.emptyDesc': 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಬುಕಿಂಗ್ ಮಾಡಿಲ್ಲ.',
    
    // Profile Page & Language Selection
    'profile.title': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'profile.subtitle': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಪಟ್ಟಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile.personalInfo': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    'profile.address': 'ಸಂಪರ್ಕ ವಿಳಾಸದ ವಿವರಗಳು',
    'profile.fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'profile.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'profile.gps': 'ಜಿಪಿಎಸ್ ಸ್ಥಾನವನ್ನು ಪತ್ತೆ ಮಾಡಿ',
    'profile.save': 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
    'profile.edit': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'profile.changePhoto': 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
    'profile.management': 'ಖಾತೆ ನಿರ್ವಹಣೆ',
    'profile.myAssets': 'ನನ್ನ ಸ್ವತ್ತುಗಳು',
    'profile.settings': 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'profile.security': 'ಗೌಪ್ಯತೆ ಮತ್ತು ಸುರಕ್ಷತೆ',
    'profile.selectLanguage': 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    'profile.logoutBtn': 'ಖಾತೆಯಿಂದ ಲಾಗೌಟ್ ಮಾಡಿ',
    'profile.changeSuccess': 'ಪ್ರೊಫೈಲ್ ವಿವರಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!',
    'profile.settingsDesc': 'ನಿಮ್ಮ ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile.myAssetsDesc': 'ನಿಮ್ಮ ಪಟ್ಟಿ ಮಾಡಲಾದ ಸ್ವತ್ತುಗಳು ಮತ್ತು ಸಂಪನ್ಮೂಲಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile.activityDesc': 'ನಿಮ್ಮ ಬುಕಿಂಗ್ ಮತ್ತು ಬಾಡಿಗೆ ಇತಿಹಾಸವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'profile.securityDesc': 'ನಿಮ್ಮ ಗೌಪ್ಯತೆ, ಭದ್ರತೆ ಮತ್ತು ರುಜುವಾತುಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile.noPhone': 'ಯಾವುದೇ ಫೋನ್ ಸಂಖ್ಯೆ ಒದಗಿಸಲಾಗಿಲ್ಲ',
    'profile.noAddress': 'ಇನ್ನೂ ಯಾವುದೇ ವಿಳಾಸವನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ.',
    'nav.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'notifications.title': 'ಅಧಿಸೂಚನೆಗಳು',
    'notifications.unreadAlerts': '{count} ಓದದ ಅಧಿಸೂಚನೆಗಳು',
    'notifications.readAll': 'ಎಲ್ಲವನ್ನೂ ಓದಿ',
    'notifications.close': 'ಫಲಕವನ್ನು ಮುಚ್ಚಿ',
    'notifications.emptyTitle': 'ಎಲ್ಲವೂ ಪೂರ್ಣಗೊಂಡಿದೆ!',
    'notifications.emptyDesc': 'ಈ ಕ್ಷಣದಲ್ಲಿ ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳು ಅಥವಾ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.',
    'rentals.filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
    'rentals.all': 'ಎಲ್ಲಾ',
    'rentals.plough': 'ನೇಗಿಲುಗಳು',
    'rentals.seeder': 'ಸೀಡರ್‌ಗಳು',
    'services.transport': 'ಸಾರಿಗೆ',
    'services.workers': 'ಕಾರ್ಮಿಕರು',
    'services.addBtn': '+ ಹೊಸ ಉಪಕರಣಗಳನ್ನು ಸೇರಿಸಿ',
    'services.placeholder': 'ಸೇವೆಗಳು, ವಾಹನಗಳು ಅಥವಾ ಕಾರ್ಮಿಕರಿಗಾಗಿ ಹುಡುಕಿ...',
    'activity.refresh': 'ಚಟುವಟಿಕೆಯನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ',
    'activity.upcomingTitle': 'ಮುಂಬರುವ ({count})',
    'activity.historyTitle': 'ಇತಿಹಾಸ ({count})',
    'activity.paid': 'ಒಟ್ಟು ಪಾವತಿಸಲಾಗಿದೆ',
    'activity.emptyLabel': 'ಯಾವುದೇ ಬುಕಿಂಗ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'activity.emptySub': 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಬುಕಿಂಗ್ ಮಾಡಿಲ್ಲ.',
    'activity.exploreRentals': 'ಬಾಡಿಗೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    'activity.status.pending': 'ಬಾಕಿ ಉಳಿದಿದೆ',
    'activity.status.confirmed': 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    'activity.status.rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'activity.status.completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'manage.title': 'ಸ್ವತ್ತುಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'manage.subtitle': 'ನಿಮ್ಮ ಪಟ್ಟಿ ಮಾಡಲಾದ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ನವೀಕರಿಸಿ',
    'manage.addBtn': 'ಸ್ವತ್ತನ್ನು ಸೇರಿಸಿ',
    'manage.tab.vehicles': 'ವಾಹನಗಳು',
    'manage.tab.equipment': 'ಉಪಕರಣಗಳು',
    'manage.tab.services': 'ಸೇವೆಗಳು',
    'manage.tab.workers': 'ಕಾರ್ಮಿಕರ ಗುಂಪುಗಳು',
    'manage.emptyTitle': 'ಯಾವುದೇ {tab} ನೋಂದಾಯಿಸಲಾಗಿಲ್ಲ',
    'manage.emptyDesc': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ಗಳಿಸಲು ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಸ್ವತ್ತುಗಳನ್ನು ಸೇರಿಸಿ',
    'manage.status.approved': 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    'manage.status.rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'manage.status.pending': 'ಬಾಕಿ ಉಳಿದಿದೆ',
    'manage.confirmDelete': 'ನೀವು ನಿಜವಾಗಿಯೂ ಈ ವಸ್ತುವನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?',
    'manage.failedDelete': 'ವಸ್ತುವನ್ನು ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ',
    'role.farmer': 'ರೈತ',
    'role.owner': 'ಮಾಲೀಕರು',
    'role.provider': 'ಪೂರೈಕೆದಾರ / ತಜ್ಞರು',
    'settings.title': 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.subtitle': 'ನಿಮ್ಮ ಭಾಷೆ ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'settings.chooseLanguage': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'settings.notificationPrefs': 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    'settings.accSecurity': 'ಖಾತೆ ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ',
    'settings.deleteAcc': 'ಖಾತೆಯನ್ನು ಅಳಿಸಿ',
  },
  mr: {
    // Nav & General
    'logo.title': 'एग्री फार्म्स',
    'nav.home': 'मुख्य पृष्ठ',
    'nav.rentals': 'भाड्याने',
    'nav.services': 'सेवा',
    'nav.activity': 'क्रियाकलाप',
    'nav.manage': 'मालमत्ता व्यवस्थापन',
    'nav.profile': 'प्रोफाइल',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',
    
    // Home Page
    'home.greeting': 'नमस्ते, {name}!',
    'home.selectField': 'तुमचे शेत निवडा',
    'home.detectLocation': 'जीपीएस स्थान शोधा',
    'home.manualLocation': 'गाव/जिल्हा प्रविष्ट करा',
    'home.searchPlaceholder': 'बियाणे, ट्रॅक्टर, फवारणी सेवा शोधा...',
    'home.searchBtn': 'शोधा',
    'home.seasonOffer': 'सीझन ऑफर',
    'home.bannerTitle': 'आजच आधुनिक कृषी सेवा बुक करा!',
    'home.bannerDesc': 'जवळपास व्यावसायिक ड्रोन फवारणी यंत्र, हार्वेस्टर आणि उच्च कार्यक्षमतेचे रोपण सहाय्यक उपलब्ध आहेत.',
    'home.exploreBtn': 'आताच एक्सप्लोर करा',
    'home.rentEquip': 'मशीनरी भाड्याने',
    'home.viewAll': 'सर्व पहा',
    'home.tractors': 'ट्रॅक्टर',
    'home.harvesters': 'हार्वेस्टर',
    'home.sprayers': 'फवारणी यंत्रे',
    'home.jcb': 'जेसीबी',
    'home.listAssetTitle': 'आपल्या मालमत्तेची सूची बनवा आणि कमवा.',
    'home.listAssetDesc': 'अतिरिक्त ट्रॅक्टर, सीडर, युटिलिटी ट्रक किंवा सानुकूल मजूर मदतनीस भाड्याने देऊन साप्ताहिक कमाई करणाऱ्या 5,000+ स्थानिक कृषी प्रदात्यांमध्ये सामील व्हा.',
    'home.registerAssetBtn': 'नोंदणी करा',
    'home.rentNowBtn': 'भाड्याने घ्या',
    'home.howItWorks': 'हे कसे कार्य करते',
    
    // Quick Tools
    'tool.weather': 'हवामान',
    'tool.cropAdvice': 'पीक सल्ला',
    'tool.mandiPrices': 'मंडी भाव',
    'tool.calculator': 'कॅल्क्युलेटर',
    'tool.comingSoon': 'ही सेवा पुढील अपडेटमध्ये उपलब्ध होईल.',
    
    // Rentals Page
    'rentals.title': 'मशीनरी भाड्याने',
    'rentals.desc': 'तुमच्या शेतासाठी सर्वोत्तम यंत्रसामग्री शोधा',
    'rentals.searchPlaceholder': 'ब्रँड किंवा श्रेणीनुसार शोधा...',
    'rentals.booked': 'बुक केलेले',
    'rentals.available': 'उपलब्ध',
    'rentals.bookNow': 'आता बुक करा',
    'rentals.empty': 'कोणतीही यंत्रसामग्री आढळली नाही',
    'rentals.adjustFilters': 'तुमचा शोध किंवा फिल्टर समायोजित करण्याचा प्रयत्न करा',
    
    // Services Page
    'services.title': 'कृषी सेवा',
    'services.desc': 'व्यावसायिक कृषी सेवा भाड्याने घ्या',
    'services.searchPlaceholder': 'कृषी सेवा शोधा...',
    'services.callBtn': 'प्रदात्याला कॉल करा',
    'services.empty': 'कोणतीही सेवा आढळली नाही',
    
    // Activity Page
    'activity.title': 'माझी क्रियाकलाप',
    'activity.desc': 'तुमच्या बुकिंगचा आणि भाड्याच्या इतिहासाचा मागोवा घ्या',
    'activity.upcoming': 'आगामी',
    'activity.history': 'इतिहास',
    'activity.totalPaid': 'एकूण भरलेले',
    'activity.empty': 'कोणतेही बुकिंग आढळले नाही',
    'activity.emptyDesc': 'तुम्ही अजून कोणतेही बुकिंग केलेले नाही.',
    
    // Profile Page & Language Selection
    'profile.title': 'माझी प्रोफाइल',
    'profile.subtitle': 'तुमचे वैयक्तिक प्रोफाइल आणि सूची व्यवस्थापित करा',
    'profile.personalInfo': 'वैयक्तिक माहिती',
    'profile.address': 'संपर्क पत्ता तपशील',
    'profile.fullName': 'पूर्ण नाव',
    'profile.phone': 'फोन नंबर',
    'profile.gps': 'जीपीएस स्थान शोधा',
    'profile.save': 'प्रोफाइल जतन करा',
    'profile.edit': 'प्रोफाइल संपादित करा',
    'profile.changePhoto': 'फोटो बदला',
    'profile.management': 'खाते व्यवस्थापन',
    'profile.myAssets': 'माझी मालमत्ता',
    'profile.settings': 'खाते सेटिंग्ज',
    'profile.security': 'गोपनीयता आणि सुरक्षा',
    'profile.selectLanguage': 'भाषा निवडा',
    'profile.logoutBtn': 'खात्यातून लॉगआउट करा',
    'profile.changeSuccess': 'प्रोफाइल तपशील यशस्वीरित्या जतन केले!',
    'profile.settingsDesc': 'तुमचे खाते सेटिंग्ज आणि प्राधान्ये व्यवस्थापित करा',
    'profile.myAssetsDesc': 'आपल्या सूचीबद्ध मालमत्तेचे आणि संसाधनांचे व्यवस्थापन करा',
    'profile.activityDesc': 'तुमच्या बुकिंगचा आणि भाड्याच्या इतिहासाचा मागोवा घ्या',
    'profile.securityDesc': 'तुमची गोपनीयता, सुरक्षा आणि क्रेडेन्शियल्स व्यवस्थापित करा',
    'profile.noPhone': 'कोणताही फोन नंबर प्रदान केला नाही',
    'profile.noAddress': 'अद्याप कोणताही पत्ता जोडलेला नाही.',
    'nav.notifications': 'अधिसूचना',
    'notifications.title': 'अधिसूचना',
    'notifications.unreadAlerts': '{count} न वाचलेले अलर्ट',
    'notifications.readAll': 'सर्व वाचा',
    'notifications.close': 'पॅनेल बंद करा',
    'notifications.emptyTitle': 'सर्व पूर्ण झाले!',
    'notifications.emptyDesc': 'या क्षणी कोणतेही नवीन सूचना किंवा अलर्ट नाहीत.',
    'rentals.filters': 'फिल्टर्स',
    'rentals.all': 'सर्व',
    'rentals.plough': 'नांगर',
    'rentals.seeder': 'सीडर',
    'services.transport': 'वाहतूक',
    'services.workers': 'मजूर',
    'services.addBtn': '+ नवीन उपकरणे जोडा',
    'services.placeholder': 'सेवा, वाहने किंवा मजूर शोधा...',
    'activity.refresh': 'क्रियाकलाप रीफ्रेश करा',
    'activity.upcomingTitle': 'आगामी ({count})',
    'activity.historyTitle': 'इतिहास ({count})',
    'activity.paid': 'एकूण भरलेले',
    'activity.emptyLabel': 'कोणतेही बुकिंग आढळले नाही',
    'activity.emptySub': 'तुम्ही अजून कोणतेही बुकिंग केलेले नाही.',
    'activity.exploreRentals': 'भाड्याने उपलब्ध संसाधने शोधा',
    'activity.status.pending': 'लंबित',
    'activity.status.confirmed': 'निश्चित झाले',
    'activity.status.rejected': 'अस्वीकृत',
    'activity.status.completed': 'पूर्ण झाले',
    'manage.title': 'मालमत्ता व्यवस्थापन',
    'manage.subtitle': 'आपल्या सूचीबद्ध संसाधनांचा मागोवा घ्या आणि अद्यतनित करा',
    'manage.addBtn': 'मालमत्ता जोडा',
    'manage.tab.vehicles': 'वाहने',
    'manage.tab.equipment': 'उपकरणे',
    'manage.tab.services': 'सेवा',
    'manage.tab.workers': 'कामगार गट',
    'manage.emptyTitle': 'कोणतेही {tab} नोंदणीकृत नाही',
    'manage.emptyDesc': 'प्लॅटफॉर्मवर कमाई सुरू करण्यासाठी तुमची मालमत्ता जोडा',
    'manage.status.approved': 'मंजूर',
    'manage.status.rejected': 'अस्वीकृत',
    'manage.status.pending': 'लंबित',
    'manage.confirmDelete': 'तुम्हाला खात्री आहे की तुम्ही हा आयटम हटवू इच्छिता?',
    'manage.failedDelete': 'आयटम हटविण्यात अयशस्वी',
    'role.farmer': 'शेतकरी',
    'role.owner': 'मालक',
    'role.provider': 'प्रदाता / तज्ञ',
    'settings.title': 'खाते सेटिंग्ज',
    'settings.subtitle': 'आपली भाषा आणि प्राधान्ये व्यवस्थापित करा',
    'settings.chooseLanguage': 'भाषा निवडा',
    'settings.notificationPrefs': 'अधिसूचना प्राधान्ये',
    'settings.accSecurity': 'खाते गोपनीयता आणि सुरक्षा',
    'settings.deleteAcc': 'खाते हटवा',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('agrifarm_web_language') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('agrifarm_web_language', lang);
  };

  const t = (key: string, fallback?: string): string => {
    const translationSet = translations[language] || translations['en'];
    return translationSet[key] || translations['en'][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
